apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigil
  labels:
    app.kubernetes.io/name: vigil
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vigil
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vigil
    spec:
      containers:
        - name: vigil
          image: 'valeriansaliou/vigil:latest'
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          # command: ['/bin/bash', '-c', '--']
          # args: ['while true; do sleep 30; done;']
          env:
            - name: CFG_ENV
              value: 'base'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          livenessProbe:
              initialDelaySeconds: 30
              periodSeconds: 180
              httpGet:
                  path: /
                  port: http
          volumeMounts:
            - name: vigil-config
              mountPath: /etc/vigil.cfg
              subPath: vigil.cfg
      volumes:
        - name: vigil-config
          configMap:
            name: vigil-config
