alias s := show
alias a := apply
alias d := delete
alias f := forward

_default:
    @just --list

show KUS_DIR:
    kubectl kustomize {{KUS_DIR}}

apply KUS_DIR:
    kubectl apply -k {{KUS_DIR}}

delete KUS_DIR:
    kubectl delete -k {{KUS_DIR}}

forward:
    kubectl port-forward deployment/vigil 8080:8080

compare:
    #!/usr/bin/env bash
    diff \
        <(kubectl kustomize overlays/staging) \
        <(kubectl kustomize overlays/production) |\
        more