alias b := build
alias v := view
alias a := apply
alias d := delete
# alias r := replace
alias f := forward

_default:
    @just --list

build KUS_DIR:
    kubectl kustomize {{KUS_DIR}}

view KUS_DIR:
    kubectl get -k {{KUS_DIR}}

apply KUS_DIR:
    kubectl apply -k {{KUS_DIR}}

delete KUS_DIR:
    kubectl delete -k {{KUS_DIR}}

# replace KUS_DIR:
#     kubectl replace -k {{KUS_DIR}}

forward port="8080":
    kubectl port-forward deployment/vigil {{port}}:8080