# nameSuffix: -production
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - path: deployment.yaml

configMapGenerator:
  - behavior: merge
    files:
      - config.cfg
    name: vigil-config
