# nameSuffix: -staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - path: deployment.yaml

configMapGenerator:
  - name: vigil-config
    behavior: merge
    files:
      - config.cfg
